var start_year = 2019;
var end_year = 2019;
var data = {
    "2019": {
        "UNITID": ["Ayers",
            "Brown",
            "Champaign",
            "City of Champaign",
            "Colfax",
            "Compromise",
            "Condit",
            "Crittenden",
            "Cunningham",
            "East Bend",
            "Harwood",
            "Hensley",
            "Kerr",
            "Ludlow",
            "Mahomet",
            "Newcomb",
            "Ogden",
            "Pesotum",
            "Philo",
            "Rantoul",
            "Raymond",
            "Sadorus",
            "St. Joseph",
            "Scott",
            "Sidney",
            "Somer",
            "South Homer",
            "Stanton",
            "Tolono",
            "Urbana"
        ],
        "poverty": [15.3,
            6.9,
            9.1,
            26.9,
            16.5,
            6.5,
            1.8,
            7.3,
            31.9,
            14,
            15.9,
            9.5,
            0,
            21.7,
            6.2,
            0.5,
            4,
            3.3,
            4.8,
            17.5,
            10.6,
            4.9,
            4.6,
            20.5,
            3.9,
            9.1,
            10,
            5.2,
            17.4,
            21.4
            ]
    }
}